import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";

export const metadata: Metadata = {
  title: "Robin Vikström portfolio",
  description: "Generated by Robin Vikström",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-slate-50 text-slate-900">
        <Navbar />
        <main className="mx-auto min-h-[80vh] max-w-5xl px-4 pt-8">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
